# Analyse de la souscription : qui répond favorablement à la campagne ?  

## Objectif  
Ce second notebook exploite la donnée nettoyée dans `01_exploration.ipynb`  
Il cherche à répondre à la problématique du projet :  
**quels profils de clients souscrivent le plus à un dépôt à terme, et comment cibler plus efficacement les prochains appels ?**  

Les indicateurs retenus ici alimenteront le dashboard Streamlit (`app.py`).  

## Point de repère  
Le taux de souscription global est d'environ **11,3 %**. Chaque segment analysé est comparé à cette référence :  
un taux nettement supérieur désigne un segment à privilégier, un taux inférieur un segment à moins solliciter.  

## Méthode  
- `y` vaut 0 ou 1 : la **moyenne** de `y` sur un groupe donne directement son taux de souscription.  
- Chaque taux est affiché avec le **volume** de clients du groupe, car un taux calculé sur un petit effectif n'est pas interprétable.  
- La variable `duration` (durée de l'appel) est volontairement **exclue de l'explication** : elle n'est connue qu'après l'appel et ne peut donc pas servir à cibler en amont.  

## Plan du notebook  
1. Chargement de la donnée nettoyée et indicateurs globaux  
2. Profil du client : métier, âge, niveau d'études  
3. Historique avec la banque : résultat de la campagne précédente (`poutcome`)  
4. Moment du contact : mois et jour de la semaine  
5. Contexte économique : Euribor et indicateurs macro  
6. Effort commercial : nombre d'appels par client (`campaign`)  
7. Synthèse : les 5 ou 6 indicateurs retenus pour le dashboard

## 1. Chargement et indicateurs globaux

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/bank_marketing_clean.csv")

In [2]:
df.shape # Affiche la forme (lignes, colonnes)

(41172, 21)

In [3]:
df.groupby("month")["y"].mean() # Regroupe les lignes par mois et calcule la moyenne de 'y' pour le groupe

month
apr    0.204943
aug    0.106073
dec    0.489011
jul    0.090389
jun    0.105115
mar    0.505495
may    0.064366
nov    0.101463
oct    0.439331
sep    0.449123
Name: y, dtype: float64

In [4]:
df.groupby("month")["y"].agg(["mean", "count"]) # Calcul le taux de souscription et la moyenne

           mean  count
month
apr    0.204943   2630
aug    0.106073   6175
dec    0.489011    182
jul    0.090389   7169
jun    0.105115   5318
mar    0.505495    546
may    0.064366  13765
nov    0.101463   4100
oct    0.439331    717
sep    0.449123    570

In [5]:
# Tri par ordre alphabétique et conversion en pourcentage
mois = df.groupby("month")["y"].agg(taux="mean", appels="count")
mois["taux"] = (mois["taux"] * 100).round(1)
mois

       taux  appels
month
apr    20.5    2630
aug    10.6    6175
dec    48.9     182
jul     9.0    7169
jun    10.5    5318
mar    50.5     546
may     6.4   13765
nov    10.1    4100
oct    43.9     717
sep    44.9     570

In [6]:
# Range les mois dans l'ordre
ordre = ["mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
mois = mois.reindex(ordre)
mois

       taux  appels
month
mar    50.5     546
apr    20.5    2630
may     6.4   13765
jun    10.5    5318
jul     9.0    7169
aug    10.6    6175
sep    44.9     570
oct    43.9     717
nov    10.1    4100
dec    48.9     182

Le jeu de données ne contient aucun appel en janvier ni en février : la campagne ne couvre que 10 mois sur 12. Les comparaisons entre mois portent donc uniquement sur ces 10 mois, et sont à nuancer car les volumes sont très inégaux.  

### Observations : taux de souscription par mois

- Mars (50,5 %), septembre, octobre et décembre affichent des taux très supérieurs à la moyenne (11,3 %), mais sur de petits volumes d'appels : ces chiffres sont à interpréter avec prudence.
- Mai, juin, juillet, août et novembre concentrent la grande majorité des appels, avec des taux de 6 à 11 %. Mai, le mois le plus appelé, a le taux le plus faible.
- Le volume d'appels est donc inversement lié au taux de réussite : on a appelé beaucoup quand ça convertissait peu.
- Limite : aucun appel en janvier et février, et les mois mélangent plusieurs années (2008-2010), donc contexte économique et saison sont confondus.

In [7]:
poutcome = df.groupby("poutcome")["y"].agg(taux="mean", appels="count")
poutcome["taux"] = (poutcome["taux"] * 100).round(1)
poutcome.sort_values("taux", ascending=False)

             taux  appels
poutcome
success      65.1    1373
failure      14.2    4252
nonexistent   8.8   35547

In [8]:
job = df.groupby("job")["y"].agg(taux="mean", appels="count")
job["taux"] = (job["taux"] * 100).round(1)
job.sort_values("taux", ascending=False)

               taux  appels
job
student        31.4     875
retired        25.3    1718
unemployed     14.2    1014
admin.         13.0   10418
unknown        11.2     330
management     11.2    2923
technician     10.8    6739
self-employed  10.5    1421
housemaid      10.0    1060
entrepreneur    8.5    1456
services        8.1    3967
blue-collar     6.9    9251

### Observations : historique (`poutcome`) et métier (`job`)

- **`poutcome`** : les clients ayant déjà souscrit lors d'une campagne précédente (`success`) reconvertissent à 65,1 %, soit près de 6 fois le taux global (11,3 %), sur un groupe de 1 373 clients. À l'inverse, 86 % des appels ont visé des clients jamais contactés, qui convertissent à 8,8 %.
- **`job`** : les étudiants (31,4 %) et les retraités (25,3 %) se démarquent nettement, avec des volumes suffisants pour être interprétés. Les `blue-collar` (6,9 %) et les `services` (8,1 %) sont sous la moyenne tout en représentant plus de 13 000 appels.
- Les `unknown` de `job` (11,2 %) sont au niveau de la moyenne : leur conservation comme modalité à part est cohérente.

In [9]:
# Création des tranches d'âge
df["tranche_age"] = pd.cut(
    df["age"],
    bins=[0, 25, 35, 45, 55, 65, 100],
    labels=["<25", "25-34", "35-44", "45-54", "55-64", "65+"],
    right=False
)

In [10]:
df["tranche_age"].isna().sum() # vérifie que tout les âges sont compris dans une borne

np.int64(0)

In [11]:
# Regroupe par taux de souscription en % et nombre d'appels par tranche
age = df.groupby("tranche_age", observed=True)["y"].agg(taux="mean", appels="count")
age["taux"] = (age["taux"] * 100).round(1)
age

             taux  appels
tranche_age
<25          24.0    1067
25-34        12.2   13683
35-44         8.7   13494
45-54         8.6    8701
55-64        13.6    3565
65+          47.3     662

### Observations : tranche d'âge

- Le taux de souscription suit une **courbe en U** : 24,0 % chez les moins de 25 ans, 47,3 % chez les 65 ans et plus, contre 8,6 à 8,7 % pour les 35-54 ans (moyenne globale : 11,3 %).
- Ces résultats recoupent ceux du métier : étudiants (31,4 %) et retraités (25,3 %).
- Les 35-54 ans concentrent plus de 22 000 appels (plus de la moitié) pour un taux inférieur à la moyenne : l'effort commercial s'est porté sur les tranches les moins réceptives.
- Limite : ce sont des associations, pas des causes. Les 65+ ne représentent que 662 clients, leur taux est à interpréter avec un peu de prudence.

In [12]:
df["nb_appels"] = df["campaign"].clip(upper=6) # création de la colonne plafonnée

In [13]:
df["nb_appels"].value_counts().sort_index() # vérifie que la colonne est bien plafonnée à 6

nb_appels
1    17634
2    10567
3     5339
4     2649
5     1599
6     3384
Name: count, dtype: int64

In [14]:
# # Taux de souscription et volume par nombre d'appels
effort = df.groupby("nb_appels")["y"].agg(taux="mean", appels="count")
effort["taux"] = (effort["taux"] * 100).round(1)
effort

           taux  appels
nb_appels
1          13.0   17634
2          11.5   10567
3          10.8    5339
4           9.4    2649
5           7.5    1599
6           5.5    3384

### Observations : effort commercial (nombre d'appels)

- Le taux de souscription diminue à chaque appel supplémentaire : 13,0 % pour les clients appelés une fois, 5,5 % pour ceux appelés 6 fois ou plus (la valeur 6 regroupe « 6 appels et plus »).
- Les 3 384 clients appelés 6 fois ou plus convertissent moins de deux fois moins que les clients appelés une seule fois.
- Insister auprès d'un même client semble donc peu rentable. Limite : ce sont des associations, un client rappelé de nombreuses fois est peut-être un client qui hésitait dès le départ.

In [15]:
df["euribor3m"].describe() # on observe la distribution

count    41172.000000
mean         3.621339
std          1.734428
min          0.634000
25%          1.344000
50%          4.857000
75%          4.961000
max          5.045000
Name: euribor3m, dtype: float64

### Contexte économique
**Euribor 3 mois** : taux d'intérêt de référence auquel les banques européennes se prêtent de l'argent à 3 mois. C'est un indicateur du contexte économique au moment de l'appel : il influence la rémunération des placements comme le dépôt à terme proposé dans cette campagne.

In [16]:
# création des tranches
df["tranche_euribor"] = pd.cut(
    df["euribor3m"],
    bins=[0, 1, 2, 10],
    labels=["<1", "1-2", "2+"],
    right=False
)

In [17]:
df["tranche_euribor"].value_counts().sort_index()

tranche_euribor
<1      3889
1-2     9603
2+     27680
Name: count, dtype: int64

In [18]:
df["tranche_euribor"].isna().sum() # Controle des NAN

np.int64(0)

In [19]:
# Taux de souscription (en %) et nombre d'appels par tranche d'Euribor
euribor = df.groupby("tranche_euribor", observed=True)["y"].agg(taux="mean", appels="count")
euribor["taux"] = (euribor["taux"] * 100).round(1)
euribor

                 taux  appels
tranche_euribor
<1               45.7    3889
1-2              15.8    9603
2+                4.8   27680

### Observations : contexte économique (Euribor 3 mois)

**Euribor 3 mois** : taux d'intérêt de référence auquel les banques européennes se prêtent de l'argent à 3 mois. C'est un indicateur du contexte économique au moment de l'appel.

- Le taux de souscription est beaucoup plus élevé quand l'Euribor est bas : 45,7 % sous 1 %, 15,8 % entre 1 et 2 %, contre 4,8 % à partir de 2 % (moyenne globale : 11,3 %).
- 27 680 appels (67 %) ont eu lieu dans la tranche la moins réceptive (`2+`).
- Les tranches `2-4` (14 clients) et `5+` (16 clients) ont été fusionnées avec `4-5` dans `2+`, car trop petites pour être interprétées.
- Limite : l'Euribor est un **contexte**, pas un levier : la banque ne choisit pas le taux du marché. Il se confond avec la période (2008 à 2010) et avec la stratégie d'appel. C'est une association, pas une cause.

## 7. Synthèse

### Réponse à la problématique
Le taux de souscription global est de 11,3 %. L'analyse montre que la campagne a concentré ses appels sur les clients les moins réceptifs, alors que plusieurs segments convertissent 2 à 6 fois mieux que la moyenne.

### Les enseignements principaux

| Axe | Segment le plus réceptif | Taux | Segment le moins réceptif | Taux |
|---|---|---|---|---|
| Historique (`poutcome`) | Anciens succès | 65,1 % | Jamais contactés | 8,8 % |
| Contexte (Euribor) | Euribor < 1 % | 45,7 % | Euribor ≥ 2 % | 4,8 % |
| Âge | 65 ans et plus | 47,3 % | 45-54 ans | 8,6 % |
| Métier | Étudiants | 31,4 % | Blue-collar | 6,9 % |
| Effort commercial | 1 appel | 13,0 % | 6 appels et plus | 5,5 % |

### Pistes de ciblage
1. **Prioriser les clients ayant déjà souscrit** : 1 373 clients à 65,1 %, alors que 86 % des appels visaient des clients jamais contactés (8,8 %).
2. **Cibler les seniors (65+) et les jeunes (< 25 ans)** : 47,3 % et 24,0 %, alors que les 35-54 ans, qui concentrent plus de la moitié des appels, convertissent à environ 8,6 %.
3. **Limiter l'insistance** : le taux baisse à chaque appel supplémentaire, de 13,0 % à 5,5 % à partir de 6 appels.
4. **Tenir compte du contexte** : quand l'Euribor est bas, la souscription explose. Ce n'est pas un levier (la banque ne le contrôle pas), mais un moment favorable pour intensifier la prospection.

### Limites
- Ce sont des **associations**, pas des causes : les données ne prouvent pas pourquoi un segment souscrit davantage.
- Les variables se **recoupent** (par exemple retraités et 65+, Euribor et période 2008-2010) : les effets ne s'additionnent pas.
- La campagne ne couvre que 10 mois sur 12, sur plusieurs années.
- `duration` a été volontairement exclue : elle n'est connue qu'après l'appel.

In [20]:
import sys
sys.path.append("..")

from src.features import add_features

df = pd.read_csv("../data/processed/bank_marketing_clean.csv")
df = add_features(df)

In [21]:
df["tranche_age"].value_counts().sort_index()

tranche_age
<25       1067
25-34    13683
35-44    13494
45-54     8701
55-64     3565
65+        662
Name: count, dtype: int64

In [22]:
df["tranche_euribor"].value_counts().sort_index()

tranche_euribor
<1      3889
1-2     9603
2+     27680
Name: count, dtype: int64

In [23]:
pd.crosstab(df["annee"], df["month"])

month   apr   aug  dec   jul   jun  mar   may   nov  oct  sep
annee
2008      0  5172   10  6681  4374    0  7761  3615   67    0
2009   2456   770  172   177   715  282  5792   357  446  267
2010    174   233    0   311   229  264   212   128  204  303

In [24]:
df.groupby("annee")["euribor3m"].mean()

annee
2008    4.817116
2009    1.232001
2010    0.813080
Name: euribor3m, dtype: float64

In [25]:
df.groupby("annee")["y"].agg(taux="mean", appels="count")

           taux  appels
annee
2008   0.048374   27680
2009   0.194770   11434
2010   0.521380    2058

### Observations : évolution par année

- Le taux de souscription passe de 4,8 % en 2008 à 19,5 % en 2009 puis 52,1 % en 2010, alors que le volume d'appels s'effondre (27 680, 11 434, 2 058).
- L'Euribor moyen baisse en parallèle (4,82, 1,23, 0,81) : l'année et l'Euribor sont deux lectures du même phénomène et ne peuvent pas être séparés.
- Plusieurs explications restent possibles (contexte économique, crise, ciblage plus fin de la banque en 2010) : les données ne permettent pas de trancher.
- L'année est déduite de l'ordre chronologique des lignes ; sa cohérence est confirmée par l'évolution de l'Euribor.